

export  const list =[{
    id:1,
    name:"Southern Global",
    location:"Embakasi",
    emptyRooms:10,
    status: "available",
},{id:2,
    name:"Southern Global",
    location:"Embakasi",
    emptyRooms:10,
    status: "available",

},{ id:3,
    name:"Southern Global",
    location:"Embakasi",
    emptyRooms:10,
    status: "available",

},{ id:4,
    name:"Southern Global",
    location:"Embakasi",
    emptyRooms:10,
    status: "available",

},{ id:5,
    name:"Southern Global",
    location:"Embakasi",
    emptyRooms:10,
    status: "available",

},{
    id:6,
    name:"Southern Global",
    location:"Embakasi",
    emptyRooms:10,
    status: "available",
},{id:7,
    name:"Southern Global",
    location:"Embakasi",
    emptyRooms:10,
    status: "available",

},{ id:8,
    name:"Southern Global",
    location:"Embakasi",
    emptyRooms:10,
    status: "available",

},{ id:9,
    name:"Southern Global",
    location:"Embakasi",
    emptyRooms:10,
    status: "available",

},{ id:10,
    name:"Southern Global",
    location:"Embakasi",
    emptyRooms:10,
    status: "available",

},{
    id:11,
    name:"Southern Global",
    location:"Embakasi",
    emptyRooms:10,
    status: "available",
},{id:12,
    name:"Southern Global",
    location:"Embakasi",
    emptyRooms:10,
    status: "available",

},{ id:13,
    name:"Southern Global",
    location:"Embakasi",
    emptyRooms:10,
    status: "available",

},{ id:14,
    name:"Southern Global",
    location:"Embakasi",
    emptyRooms:10,
    status: "available",

},{ id:15,
    name:"Southern Global",
    location:"Embakasi",
    emptyRooms:10,
    status: "available",

},{
    id:16,
    name:"Southern Global",
    location:"Embakasi",
    emptyRooms:10,
    status: "available",
},{id:17,
    name:"Southern Global",
    location:"Embakasi",
    emptyRooms:10,
    status: "available",

},{ id:18,
    name:"Southern Global",
    location:"Embakasi",
    emptyRooms:10,
    status: "available",

},{ id:19,
    name:"Southern Global",
    location:"Embakasi",
    emptyRooms:10,
    status: "available",

},{ id:20,
    name:"Southern Global",
    location:"Embakasi",
    emptyRooms:10,
    status: "available",

}]